config/routes.rb
JqueryRails::Application.routes.draw do
  resources :comments do
    collection do
      get :search
    end
  end

  root :to => "comments#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  has_attached_file :attachment
  validates :subject, :body, :presence => true
  validates_presence_of :subject


  searchable do
  	text :subject
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  respond_to :html, :xml, :json
  respond_to :js, :only => [:create, :update, :destroy]
  # GET /comments
  # GET /comments.xml
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.xml
  def show
    @comment = Comment.find(params[:id])
  end

  # GET /comments/new
  # GET /comments/new.xml
  def new
    @comment = Comment.new
    #respond_with(@comment, :layout => false)
    respond_with do |format|
      format.html { render :layout => ! request.xhr? }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.xml
  def create
    @comment = Comment.create(comment_params)
    if request.xhr? || remotipart_submitted?
      sleep 1 if params[:pause]
      render :layout => false, :template => (params[:template] == 'escape' ? 'comments/escape_test' : 'comments/create'), :status => (@comment.errors.any? ? :unprocessable_entity : :ok)
    else
      redirect_to comments_path
    end
  end

  # PUT /comments/1
  # PUT /comments/1.xml
  def update
    @comment = Comment.find(params[:id])
    respond_with do |format|
      format.html{ redirect_to @comment }
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.xml
  def destroy
    @comment = Comment.destroy(params[:id])
  end

  # GET /books/search
  # GET /books/search.xml
  def search
    @comments = Comment.search do
      keywords params[:query]
  end.results

    respond_to do |format|
      format.html { render :action => "index" }
      format.xml  { render :xml => @comments }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:subject, :body, :attachment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<tr class='comment' id='comment-<%= comment.id %>'>
  <td></td>
  <td class="subject"><%= comment.subject %></td>
  <td class="body"><%= comment.body %></td>
  <td class="time"><%= comment.created_at %></td>
  <td class="file"><%= link_to comment.attachment_file_name, comment.attachment.url if comment.attachment? %></td>

</tr>

app/views/comments/_form.html.erb
<%= form_for(@comment, :remote => (params[:action] == 'new' ? true : false)) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <div class="field">
      <%= f.label :name, 'Предмет', :class => 'required' %><br />
      <%= f.text_field :subject, :required => true %>
    </div>
    <div class="field">
      <%= f.label :name, 'Дата', :class => 'required' %><br />
      <%= f.text_field :body, :required => true %>
    </div>
    <% if params[:attachment] %>
      <div class="field">
        <%= f.label :name, 'Файл' %><br />
        <%= f.file_field :attachment %>
      </div>
    <% end %>
  </fieldset><br />

  <div class="actions">
    <%= f.submit 'Отправить файл', :data => {:'disable-with' => "Submitting..."} %>
  </div>
<% end %>

app/views/comments/_new_comment_links.html.erb
<div id='new-comment-links'>
  <%= link_to 'Добавить файл', new_comment_path(:attachment => true), :remote => true, :'data-type' => 'html', :id => 'new-comment-attachment-link' %>
</div>

app/views/comments/create.html.erb
<span>
HTML response:
</span>

<table>
<%= render @comment %>
</table>

app/views/comments/create.js.erb
<%= remotipart_response do %>
  <% unless @comment.errors.any? %>
    $('#comments').append( '<%= escape_javascript(
      render @comment
    ) %>' );
    $('#new-comment-form-container').find('input:not(:submit),select,textarea').val('');
    <% if request.put? %>
        $('#comments').after('PUT request!');
    <% end %>
  <% else %>
    var $form = $('#new_comment'),
        $errorDiv = $('<div id="error_explanation">'),
        $errorList = $('<ul>');
    <% @comment.errors.full_messages.each do |msg| %>
      $errorList.append('<li><%= escape_javascript msg %></li>');
    <% end %>
    $form.find('#error_explanation').remove();
    $form.prepend($errorDiv.append($errorList));
  <% end %>
<% end %>

app/views/comments/create.json.erb
<%= @comment.to_json %>

app/views/comments/destroy.js.erb
$('#comment-<%= @comment.id %>').remove();

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/escape_test.html.erb
<%= text_field_tag :quote, '"' %>

app/views/comments/index.html.erb
<%= render 'new_comment_links' %>

<%= form_tag search_comments_path, :method => :get do %>
<p>
  <%= text_field_tag :query, params[:query] %> 
  <%= link_to "Поиск", search_comments_path %>
</p>
<% end %>


<h3><a href="http://localhost:3000/comments">Репозиторий Международного Университета Информационных Технологий</a></h3>

<table id='comments'>
  <%= render @comments %>
</table>

app/views/comments/new.html.erb
<div id='new-comment-form-container'>
  <h3>Новый файл</h3> 

  
  <%= render 'form' %>
  <%= link_to 'Закрыть', comments_path, :id => 'cancel-button' %>

  
</div>

app/views/comments/show.html.erb
<table>
  <tr>
    <th>Subject</th>
    <th>Body</th>
    <th>Attachment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <%= render @comment %>
</table>

<br />

<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JqueryRails</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>